In [1]:
#Imports
import numpy as np
import pandas as pd
#pip install easygui
import easygui as eg
#pip install inquirer
#import inquirer
#!pip install cvxpy
import cvxpy as cp
from functools import reduce
import operator

In [2]:
#User input possibility
#max_budget = input("Enter Maximum Budget: ")
#min_rating = input("Enter Minimum Rating: ")
#min_calories = input("Enter Minimum Calories: ")
#max_calories = input("Enter Maximum Calories: ")
#min_fat = input("Enter Minimum Fat: ")
#max_fat = input("Enter Maximum Fat: ")
#min_protein = input("Enter Minimum Protein: ")
#max_protein = input("Enter Maximum Protein: ")
#min_sodium = input("Enter Minimum Sodium: ")
#max_sodium = input("Enter Maximum Sodium: ")
#min_veg = input("Enter Minimum Vegetable Portions: ")
#max_veg = input("Enter Maximum Vegetable Portions: ")
#min_fruit = input("Enter Minimum Fruit Portions: ")
#max_fruit = input("Enter Maximum Fruit Portions: ")
#diet_choice = input("Enter Diet Type: ")  #options: 'healthy','pescatarian', 'paleo', 'vegan', 'vegetarian', 'wheat/gluten-free'

In [3]:
#Default values for constraints
min_rating = 3
min_calories = 1800
max_calories = 2100
min_fat = 46
max_fat = 80
min_protein = 40
max_protein = 50
min_sodium = 0
max_sodium = 1500
min_veg = 2
max_veg = 5
min_fruit = 2
max_fruit = 5
diet_choice = 'wheat/gluten-free' #options: 'healthy','pescatarian', 'paleo', 'vegan', 'vegetarian', 'wheat/gluten-free'

In [4]:
#Import data
data = pd.read_csv('recipies.csv')
#Remove irrelevant columns
remove_columns =['#cakeweek','#wasteless','22-minute meals','3-ingredient recipes','30 days of groceries','advance prep required','alabama','alaska','anthony bourdain','arizona','aspen',  'atlanta','australia','back to school','backyard bbq','bastille day','beverly hills','birthday','blender','boil','bon appÃ©tit','bon appï¿½ï¿½tit','boston','braise','broil','brooklyn','buffalo','buffet','bulgaria','california','calvados','cambridge','camping', 'canada','candy thermometer','casserole/gratin','chicago','chile','chill','christmas','christmas eve','cinco de mayo','cocktail', 'cocktail party','coffee grinder','colorado','columbus','connecticut','cookbook critic','costa mesa','cuba','dallas','deep-fry','denver','diwali', 'dominican republic','dorie greenspan', 'double boiler', 'easter', 'edible gift', 'egypt', 'engagement party', 'england', 'entertaining', 'epi + ushg','epi loves the microwave', 'fall', 'family reunion', "father's day", 'flaming hot summer', 'florida', 'food processor','fourth of july', 'france', 'frankenrecipe', 'freeze/chill', 'freezer food', 'friendsgiving', 'fritter', 'frozen dessert', 'fry', 'game', 'georgia', 'germany', 'gourmet', 'graduation', 'grill', 'grill/barbecue', 'guam', 'haiti', 'halloween','hanukkah', 'harpercollins', 'hawaii', 'healdsburg', 'hollywood', 'house & garden', 'house cocktail', 'houston', 'ice cream machine', 'idaho', 'illinois', 'indiana', 'iowa', 'ireland', 'israel', 'italy', 'jamaica', 'japan', 'juicer', 'kansas', 'kansas city', 'kentucky', 'kentucky derby', 'kitchen olympics', 'kosher for passover', 'kumquat', 'kwanzaa', 'labor day', 'lancaster','las vegas', 'london', 'long beach', 'los angeles', 'louisiana', 'louisville', 'lunar new year', 'maine', 'mandoline', 'mardi gras', 'marinate', 'maryland', 'massachusetts', 'mexico', 'miami', 'michigan', 'microwave','minneapolis','minnesota','mississippi', 'missouri', 'mixer', "mother's day", 'nancy silverton', 'nebraska', 'new hampshire', 'new jersey', 'new mexico', 'new orleans', "new year's day", "new year's eve", 'new york','no-cook', 'north carolina', 'ohio', 'oklahoma', 'oktoberfest','one-pot meal', 'oregon', 'oscars', 'pacific palisades', 'pan-fry', 'parade', 'paris', 'party', 'pasadena', 'passover', 'pasta maker', 'pennsylvania', 'persian new year', 'peru', 'philippines', 'pittsburgh', 'poach', 'poker/game night', 'portland', 'pressure cooker', 'providence', 'quick & easy', 'ramadan', 'ramekin', 'raw', 'rhode island', 'rosh hashanah/yom kippur', 'san francisco', 'sandwich theory', 'santa monica', 'sautÃ©', 'seattle', 'self', 'shower', 'side', 'simmer', 'skewer', 'slow cooker', 'smoker', 'south carolina', 'spain', 'spring', 'st. louis', "st. patrick's day", 'steam', 'stew', 'summer', 'super bowl', 'suzanne goin', 'switzerland', 'tailgating', 'tennessee', 'tested & improved', 'texas', 'thanksgiving', 'utah', "valentine's day", 'vermont', 'virginia', 'washington', 'washington, d.c.', 'wedding', 'weelicious', 'west virginia', 'westwood', 'windsor', 'winter', 'wisconsin', 'wok', 'cookbooks', 'leftovers',"hors d'oeuvre",'mortar and pestle','non-alcoholic','picnic', 'poppy','port','potluck', 'prune','punch', 'purim','rub', 'shavuot', 'snapper', 'spritzer', 'sukkot', 'yonkers','alcoholic','anniversary','bake','brine','caraway','condiment/spread','cook like a diner','digestif', 'aperitif', 'dairy','appetizer','brownie','brunch','cake','cobbler/crumble','condiment','cookie', 'cookies','crï¿½ï¿½me de cacao', 'cupcake','drink','drinks','dip','fruit juice','grains','hominy/cornmeal/masa','hot drink','liqueur', 'lasagna', 'leafy green','muffin','organic','pizza','pastry','pancake','potato salad','pie','quiche', 'quick and healthy','roast', 'root vegetable','sorbet','stuffing/dressing', 'stir-fry', 'spirit','smoothie', 'sauce', 'salad', 'snack week', 'soufflÃ©/meringue','soup/stew','salad dressing','tart','amaretto','mezcal','anise','midori','rosemary','beer','nutmeg','sage','bitters','omelet','salsa','brandy','oregano','tamarind','campari','paprika','tortillas','candy','tea','cardamom','tequila','chambord','thyme','champagne','triple sec','chartreuse','vanilla','cinnamon','vermouth','clove','vodka','cognac/armagnac','whiskey','coriander','wasabi','cumin','white wine','curry','taco','eau de vie','red wine','egg nog','rum','fortified wine','saffron','frangelico','sake','gin','pernod','ginger','sandwich','grappa','sangria','martini','scotch','mayonnaise','seed','marsala','sherry','margarita','sparkling wine','kahlÃºa','spice','iced coffee','sourdough','iced tea','bourbon','bread','custard','herb','ice cream','macaroni and cheese','marinade','wine','tree nut free', 'sugar conscious', 'soy free','peanut free','no sugar added', 'no meat, no problem','low fat', 'dairy free','fat free','low sodium', 'low cholesterol',  'low/no sugar', 'low sugar','kidney friendly','kosher', 'kid-friendly','high fiber', 'low cal','low carb']	
data = data.drop(remove_columns, axis=1)
#set(data.columns.values.tolist()) #To see list of columns
#Remove empty columns
calculation = pd.Series(data.sum())
remove_empty_columns = list(calculation[calculation == 0].index)
data = data.drop(remove_empty_columns, axis=1)
#remove leading and trailing spaces
data['title'] = data['title'].str.strip()
#remove duplicate recipies by title
data = data.drop_duplicates(subset=['title'])
#update most missing meal types
updates_meal_type = pd.read_csv('update_meal_type.csv',sep=';')
#remove duplicate recipies by title and merge
updates_meal_type = updates_meal_type.drop_duplicates(subset=['title'])
data = data.merge(updates_meal_type, how='left', on='title')
data['breakfast'] = data[['breakfast', 'breakfast2']].max(axis=1)
data['lunch'] = data[['lunch', 'lunch2']].max(axis=1)
data['dinner'] = data[['dinner', 'dinner2']].max(axis=1)
data['dessert'] = data[['dessert', 'dessert2']].max(axis=1)
data['snack'] = data[['snack', 'snack2']].max(axis=1)
data = data.drop(['breakfast2','lunch2','dinner2','dessert2','snack2'], axis=1)
data.head()

,title,rating,calories,protein,fat,sodium,almond,anchovy,apple,apple juice,...,watermelon,wheat/gluten-free,whole wheat,wild rice,yellow squash,yogurt,yuca,zucchini,snack,turkey
0,"Lentil, Apple, and Turkey Wrap",2.500,426.0,30.0,7.0,559.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Boudin Blanc Terrine with Red Onion Confit,4.375,403.0,18.0,23.0,1439.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Potato and Fennel Soup Hodge,3.750,165.0,6.0,7.0,165.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Mahi-Mahi in Tomato Olive Sauce,5.000,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Spinach Noodle Casserole,3.125,547.0,20.0,32.0,452.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
data.shape

(17736, 290)

In [6]:
#Remove incomplete rows
data = data.dropna(subset=['title','rating','calories','protein','fat','sodium','vegetable','fruit','snack', 'breakfast','dessert','dinner', 'lunch','healthy','pescatarian', 'paleo', 'vegan', 'vegetarian', 'wheat/gluten-free'])
data.shape

(14015, 290)

In [7]:
#Remove rows with values inconsistent with daily suggestions
data = data[data['calories']<1000] #daily approx 2000
data = data[data['sodium']<1000] #daily approx 2300mg
data = data[data['protein']<40] #daily approx 56g
data = data[data['fat']<40]#daily approx 44 - 77
data.shape

(9441, 290)

In [8]:
#Set index
data=data.set_index('title')
data.head()

,rating,calories,protein,fat,sodium,almond,anchovy,apple,apple juice,apricot,...,watermelon,wheat/gluten-free,whole wheat,wild rice,yellow squash,yogurt,yuca,zucchini,snack,turkey
title,,,,,,,,,,,,,,,,,,,,,
"Lentil, Apple, and Turkey Wrap",2.500,426.0,30.0,7.0,559.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Potato and Fennel Soup Hodge,3.750,165.0,6.0,7.0,165.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Spinach Noodle Casserole,3.125,547.0,20.0,32.0,452.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Yams Braised with Cream, Rosemary and Nutmeg",3.750,256.0,4.0,5.0,30.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Beef Tenderloin with Garlic and Brandy,4.375,174.0,11.0,12.0,176.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
#Check all ingredients are used in at least one recipe
ingredients = ['almond', 'anchovy', 'apple', 'apple juice', 'apricot', 'artichoke', 'arugula', 'asian pear', 'asparagus', 'avocado', 'bacon', 'banana', 'barley', 'basil', 'bass', 'bean', 'beef', 'beef rib', 'beef shank', 'beef tenderloin', 'beet', 'bell pepper', 'berry', 'biscuit', 'blackberry', 'blue cheese', 'blueberry', 'bok choy', 'bran', 'breadcrumbs', 'brie', 'brisket', 'broccoli', 'broccoli rabe', 'brown rice', 'brussel sprout', 'bulgur', 'butter', 'buttermilk', 'butternut squash', 'butterscotch/caramel', 'cabbage', 'cantaloupe', 'capers', 'carrot', 'cashew', 'cauliflower', 'caviar', 'celery', 'chard', 'cheddar', 'cheese', 'cherry', 'chestnut', 'chicken', 'chickpea', 'chile pepper', 'chive', 'chocolate', 'cilantro', 'citrus', 'clam', 'coconut', 'cod', 'coffee', 'collard greens', 'corn', 'cornmeal', 'cottage cheese', 'couscous', 'crab', 'cranberry', 'cranberry sauce', 'cream cheese', 'crÃ©me de cacao', 'cucumber', 'currant', 'date', 'dill', 'dried fruit', 'duck', 'egg', 'eggplant', 'endive', 'escarole', 'fennel', 'feta', 'fig', 'fish', 'fontina', 'garlic','goat cheese', 'goose', 'gouda', 'granola', 'grape', 'grapefruit', 'green bean', 'green onion/scallion', 'ground beef', 'ground lamb', 'guava', 'halibut', 'ham', 'hamburger', 'hazelnut', 'honey', 'honeydew', 'horseradish', 'hot pepper', 'hummus', 'jalapeÃ±o', 'jam or jelly', 'jerusalem artichoke', 'jÃ­cama', 'kale', 'kirsch', 'kiwi', 'lamb', 'lamb chop', 'lamb shank', 'leek', 'legume', 'lemon', 'lemon juice', 'lemongrass', 'lentil', 'lettuce', 'lima bean', 'lime', 'lime juice', 'lingonberry', 'lobster', 'lychee', 'macadamia nut', 'mango', 'maple syrup', 'marscarpone', 'marshmallow', 'meat', 'meatball', 'meatloaf', 'melon', 'milk/cream', 'mint', 'molasses', 'monterey jack', 'mozzarella', 'mushroom', 'mussel', 'mustard', 'mustard greens', 'nectarine', 'noodle', 'nut', 'oat', 'oatmeal', 'octopus', 'okra', 'olive', 'onion', 'orange', 'orange juice', 'orzo', 'oyster', 'papaya', 'parmesan', 'parsley', 'parsnip', 'passion fruit', 'pasta', 'pea', 'peach', 'peanut', 'peanut butter', 'pear', 'pecan', 'pepper', 'persimmon', 'phyllo/puff pastry dough', 'pickles', 'pine nut', 'pineapple', 'pistachio', 'plantain', 'plum', 'poblano', 'pomegranate', 'pomegranate juice', 'pork', 'pork chop', 'pork rib', 'pork tenderloin', 'potato', 'poultry', 'poultry sausage', 'prosciutto', 'pumpkin', 'quail', 'quince', 'quinoa', 'rack of lamb', 'radicchio', 'radish', 'raisin', 'raspberry', 'rhubarb', 'rice', 'ricotta', 'rutabaga', 'rye', 'salmon', 'sausage', 'scallop', 'seafood', 'semolina', 'sesame', 'sesame oil', 'shallot', 'shellfish', 'shrimp', 'sour cream', 'soy', 'soy sauce', 'spinach', 'squash', 'squid', 'steak', 'stock', 'strawberry', 'sugar snap pea', 'sweet potato/yam', 'swiss cheese', 'swordfish', 'tangerine', 'tapioca', 'tarragon', 'tilapia', 'tofu', 'tomatillo', 'tomato', 'tree nut', 'tropical fruit', 'trout', 'tuna', 'turnip', 'veal', 'venison', 'vinegar', 'walnut', 'watercress', 'watermelon', 'whole wheat', 'wild rice', 'yellow squash', 'yogurt', 'yuca', 'zucchini', 'turkey']
data[ingredients].sum().sort_values()

orzo             1.0
venison          1.0
meatloaf         1.0
caviar           1.0
meatball         1.0
               ...
cheese         638.0
tomato         882.0
onion          963.0
egg            979.0
milk/cream    1119.0
Length: 259, dtype: float64

In [10]:
#Check all recipies have ingredients
no_ing = data[ingredients].sum(axis=1).sort_values()[lambda x: x==0].index.tolist()
data.drop(no_ing, inplace=True)

In [11]:
data.shape

(9122, 289)

In [12]:
#check all recipies have one and only one type assigned
incorrect_type = data[['breakfast','lunch','snack','dinner','dessert']].sum(axis=1).sort_values()[lambda x: x!=1].index.tolist()
data.drop(incorrect_type, inplace=True)

In [13]:
data.shape

(7274, 289)

In [14]:
#For calculating recipie prices - used during implementation to add later the recipe prices in the next cell
#data_ing = data[ingredients]
#data_ing.to_csv('data_with_ingredients.csv',sep=';')

In [15]:
#Import recipe prices and define c variable for objective function
c = pd.read_csv('recipe_prices.csv', names=['Recipe','Price'],sep=';')
c=c.set_index('Recipe')
c.values

array([[14.606],
       [ 1.525],
       [ 5.165],
       ...,
       [15.271],
       [ 5.   ],
       [10.37 ]])

In [16]:
c.shape

(7274, 1)

In [17]:
for i in range(0,7):
    #Define contraints
    #Redefine for each day/loop since we are removing recipes
    T = data[data.columns.intersection(['breakfast','lunch','snack','dinner','dessert'])].T
    if (diet_choice!=''):
        f = data[data.columns.intersection([diet_choice])].T
    A = data[data.columns.intersection(['rating','calories','protein','fat','sodium','vegetable','fruit'])].T
    max_rating = 5
    b_max = np.array([max_rating,max_calories,max_fat,max_protein,max_sodium,max_veg,max_fruit])
    d_min = np.array([min_rating,min_calories,min_fat,min_protein,min_sodium,min_veg,min_fruit])
    #Incorporate all inequality constraints in one matrix and vector
    Aineq = pd.concat([A,-A]).to_numpy()
    bineq = np.concatenate([b_max,-d_min])
    #Incorporate all equality constraints in one matrix and vector
    if (diet_choice!=''):
        Aeq = np.vstack((np.ones(data.shape[0]).T,T.to_numpy(),f.to_numpy()))
        beq = [5,1,1,1,1,1,5]
    else:
        Aeq = np.vstack((np.ones(data.shape[0]).T,T.to_numpy()))
        beq = [5,1,1,1,1,1]
    #Define and solve the CVXPY problem
    x = cp.Variable(data.shape[0])
    objective = cp.Minimize(c.values.T@x)
    constraints = [Aineq @ x <= bineq, Aeq @ x == beq, x >= 0]
    prob = cp.Problem(objective,constraints)
    prob.solve(solver=cp.ECOS) 

    #Print results
    print('Day',i+1,':')
    print("\nThe optimal value is", prob.value)
    results = pd.DataFrame(data=x.value, index=data.index, columns=['Choice'])
    results = results.merge(T.T, left_on='title', right_on='title')
    #results = results.merge(f.T, left_on='title', right_on='title')
    results = results.sort_values(by='Choice',ascending=False)[0:5]
    results = results.merge(c.loc[results.index,'Price'], left_on='title', right_on='title')
    price = reduce(operator.add, c.loc[results.index,'Price'])
    print("\nThe actual prince is", price)
    display(results)
    #Remove selected recipies from data set and prices vector
    data.drop(results.index.tolist(), axis=0, inplace=True)
    c.drop(results.index.tolist(), axis=0, inplace=True)

Day 1 :

The optimal value is 11.519475250600932

The actual prince is 6.45

,Choice,breakfast,dessert,dinner,lunch,snack,Price
title,,,,,,,
Dried Cranberry Compote,1.000000,0.0,1.0,0.0,0.0,0.0,1.500
Crispy Baby Yukon Gold Potatoes,0.873578,0.0,0.0,0.0,0.0,1.0,0.825
Fresh Vegetable Pickles,0.740015,0.0,0.0,1.0,0.0,0.0,0.800
"Yogurt with Granola, Tropical Fruit, and Crystallized Ginger",0.613593,1.0,0.0,0.0,0.0,0.0,2.000
Potato-Parsnip Salad with Aquavit Dressing,0.524917,0.0,0.0,0.0,1.0,0.0,1.325

Day 2 :

The optimal value is 15.499373151543432

The actual prince is 16.317

,Choice,breakfast,dessert,dinner,lunch,snack,Price
title,,,,,,,
Roasted-Beet and Apple Relish,1.000000,0.0,0.0,0.0,0.0,1.0,4.000
Banana Smoothie,0.971356,1.0,0.0,0.0,0.0,0.0,1.442
Raspberry Sundaes with Chocolate Sauce and Roasted Almonds,0.899564,0.0,1.0,0.0,0.0,0.0,1.500
"Chinese Black Rice, Orange, and Avocado Salad",0.899564,0.0,0.0,1.0,0.0,0.0,6.851
JalapeÃ±o-Glazed Chicken Breasts,0.514327,0.0,0.0,0.0,1.0,0.0,2.524

Day 3 :

The optimal value is 23.787030275541888

The actual prince is 20.482000000000003

,Choice,breakfast,dessert,dinner,lunch,snack,Price
title,,,,,,,
Strawberry Rhubarb Crumble Smoothie,1.000000,1.0,0.0,0.0,0.0,0.0,6.511
Cornbread Stuffing with Fresh and Dried Fruit,1.000000,0.0,0.0,0.0,0.0,1.0,6.200
Cooked Rice,0.895930,0.0,0.0,1.0,0.0,0.0,0.871
Sugar Snap Pea and Cabbage Slaw,0.755699,0.0,0.0,0.0,1.0,0.0,4.100
Coconut and Lychee Sorbet,0.551458,0.0,1.0,0.0,0.0,0.0,2.800

Day 4 :

The optimal value is 27.822870124757323

The actual prince is 23.879

,Choice,breakfast,dessert,dinner,lunch,snack,Price
title,,,,,,,
Cranberry-Orange Marmalade,1.000000,1.0,0.0,0.0,0.0,0.0,6.480
Riesling-Braised Sauerkraut and Apples,0.922836,0.0,0.0,0.0,0.0,1.0,8.803
Sorbet in Grapefruit Cups,0.734678,0.0,1.0,0.0,0.0,0.0,1.600
Vegetables and Hard-Boiled Eggs with Anchovy Cream,0.725309,0.0,0.0,1.0,0.0,0.0,6.196
Grilled Corn on the Cob with Glove-Box Recado,0.357347,0.0,0.0,0.0,1.0,0.0,0.800

Day 5 :

The optimal value is 30.01030055324099

The actual prince is 35.655

,Choice,breakfast,dessert,dinner,lunch,snack,Price
title,,,,,,,
"Melon, Nectarine, Grape, and Plum Compote",1.000000,1.0,0.0,0.0,0.0,0.0,7.000
Mango-Lime Ice,0.803137,0.0,1.0,0.0,0.0,0.0,7.575
"Cauliflower Pizzas With Mozzarella, Kale, and Lemon",0.755706,0.0,0.0,1.0,0.0,0.0,6.900
"Bitter Greens with Carrots, Turnips, and Oranges",0.590956,0.0,0.0,0.0,1.0,0.0,4.580
Cabbage and Apple Slaw with Butter-Toasted Pecans,0.545737,0.0,0.0,0.0,0.0,1.0,9.600

Day 6 :

The optimal value is 39.89761582294995

The actual prince is 47.370999999999995

,Choice,breakfast,dessert,dinner,lunch,snack,Price
title,,,,,,,
Spinach-Pineapple-Mint Juice,1.000000,1.0,0.0,0.0,0.0,0.0,3.500
Quinoa Brown Rice Sushi,0.878147,0.0,0.0,1.0,0.0,0.0,13.571
Dried Fruits and Nuts,0.632087,0.0,0.0,0.0,0.0,1.0,19.000
Peach-Raspberry Milk Shake,0.486967,0.0,1.0,0.0,0.0,0.0,6.500
Shaved Asparagus with Parmesan Vinaigrette,0.386028,0.0,0.0,0.0,1.0,0.0,4.800

Day 7 :

The optimal value is 57.03979251022405

The actual prince is 58.351

,Choice,breakfast,dessert,dinner,lunch,snack,Price
title,,,,,,,
Orange-Spice Fruit Compote,1.000000,0.0,1.0,0.0,0.0,0.0,9.480
Seared Tuna with Wasabi-Coconut Sauce and Roasted-Pepper Rice Pilaf,0.880907,0.0,0.0,1.0,0.0,0.0,10.871
"Cauliflower ""Couscous"" With Dried Fruit and Almonds",0.784725,0.0,0.0,0.0,0.0,1.0,13.000
Bigeye Tuna with Red Currant and Apple Vinaigrette and Snap Peas,0.665632,0.0,0.0,0.0,1.0,0.0,16.000
Tapioca with Stewed Apples and Apricots,0.522707,1.0,0.0,0.0,0.0,0.0,9.000